/// ZuraLog — Meal Walkthrough Screen.
///
/// A full-screen, one-question-at-a-time walkthrough that refines a parsed
/// meal using guided follow-up questions generated by the AI. Each question
/// maps to one of six component renderers (slider, button group, number
/// stepper, size picker, yes/no, free text). Unknown component types fall
/// back to a safe placeholder.
///
/// Navigation model:
///   - Back arrow dims on the first question (disabled).
///   - "Skip all" fills every remaining question with its default and pops.
///   - Bottom bar: Back (secondary), Skip (text), Next / Finish (primary).
///
/// Finishing pops the screen and returns the accumulated answers map to the
/// caller, keyed by [GuidedQuestion.id].
library;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:go_router/go_router.dart';

import 'package:zuralog/core/theme/theme.dart';
import 'package:zuralog/features/nutrition/domain/guided_question.dart';
import 'package:zuralog/features/nutrition/domain/nutrition_models.dart';
import 'package:zuralog/shared/widgets/animations/z_fade_slide_in.dart';
import 'package:zuralog/shared/widgets/buttons/z_button.dart';
import 'package:zuralog/shared/widgets/cards/zuralog_card.dart';
import 'package:zuralog/shared/widgets/inputs/z_chip.dart';
import 'package:zuralog/shared/widgets/inputs/z_number_stepper.dart';
import 'package:zuralog/shared/widgets/inputs/z_slider.dart';
import 'package:zuralog/shared/widgets/inputs/z_text_area.dart';

// ── MealWalkthroughScreen ───────────────────────────────────────────────────

/// Walkthrough that asks the user one guided question at a time.
class MealWalkthroughScreen extends StatefulWidget {
  /// Creates a [MealWalkthroughScreen] with the given [args].
  const MealWalkthroughScreen({super.key, required this.args});

  /// The questions, foods, and any pre-filled answers.
  final MealWalkthroughArgs args;

  @override
  State<MealWalkthroughScreen> createState() => _MealWalkthroughScreenState();
}

class _MealWalkthroughScreenState extends State<MealWalkthroughScreen> {
  final PageController _pageController = PageController();

  /// Accumulated answers keyed by question id.
  late final Map<String, dynamic> _answers;

  /// Text controllers for free-text questions, keyed by question id.
  ///
  /// Owned and disposed by the screen so they survive PageView rebuilds.
  final Map<String, TextEditingController> _textControllers = {};

  int _currentIndex = 0;

  @override
  void initState() {
    super.initState();
    _answers = Map<String, dynamic>.of(widget.args.initialAnswers);

    // Pre-seed answers with defaults so Next works even if the user does not
    // interact with the component. Renderers that need mutation (slider,
    // stepper) call [_setAnswer] on every change.
    for (final q in widget.args.questions) {
      _answers.putIfAbsent(q.id, () => q.defaultValue);
    }
  }

  @override
  void dispose() {
    _pageController.dispose();
    for (final controller in _textControllers.values) {
      controller.dispose();
    }
    super.dispose();
  }

  // ── Answer helpers ────────────────────────────────────────────────────────

  void _setAnswer(String questionId, dynamic value) {
    setState(() => _answers[questionId] = value);
  }

  /// Returns (or lazily creates) the [TextEditingController] for a free-text
  /// question. Keyed by [questionId] so it survives navigation.
  TextEditingController _controllerFor(String questionId, Object? initial) {
    return _textControllers.putIfAbsent(
      questionId,
      () => TextEditingController(text: initial?.toString() ?? ''),
    );
  }

  // ── Navigation ────────────────────────────────────────────────────────────

  void _goNext() {
    HapticFeedback.lightImpact();
    final isLast = _currentIndex >= widget.args.questions.length - 1;

    // Flush any free-text answer for the current question before advancing.
    final current = widget.args.questions[_currentIndex];
    if (current.componentType == GuidedComponentType.freeText) {
      final controller = _textControllers[current.id];
      if (controller != null) {
        _answers[current.id] = controller.text;
      }
    }

    if (isLast) {
      _finish();
      return;
    }

    setState(() => _currentIndex += 1);
    _pageController.nextPage(
      duration: const Duration(milliseconds: 260),
      curve: Curves.easeOutCubic,
    );
  }

  void _goBack() {
    if (_currentIndex == 0) return;
    HapticFeedback.selectionClick();
    setState(() => _currentIndex -= 1);
    _pageController.previousPage(
      duration: const Duration(milliseconds: 260),
      curve: Curves.easeOutCubic,
    );
  }

  void _skipCurrent() {
    HapticFeedback.selectionClick();
    final current = widget.args.questions[_currentIndex];
    _answers[current.id] = current.defaultValue;
    _goNext();
  }

  void _skipAll() {
    HapticFeedback.mediumImpact();
    // Fill every remaining unanswered question with its default.
    for (var i = _currentIndex; i < widget.args.questions.length; i++) {
      final q = widget.args.questions[i];
      _answers[q.id] = q.defaultValue;
    }
    _finish();
  }

  void _finish() {
    // Flush any free-text value that was not committed.
    for (final q in widget.args.questions) {
      if (q.componentType == GuidedComponentType.freeText) {
        final controller = _textControllers[q.id];
        if (controller != null) {
          _answers[q.id] = controller.text;
        }
      }
    }
    context.pop<Map<String, dynamic>>(_answers);
  }

  // ── Build ────────────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    final colors = AppColorsOf(context);
    final questions = widget.args.questions;
    final total = questions.length;

    // Empty questions list → nothing to ask, pop immediately on next frame.
    if (total == 0) {
      WidgetsBinding.instance.addPostFrameCallback((_) {
        if (mounted) context.pop<Map<String, dynamic>>(_answers);
      });
      return Scaffold(
        backgroundColor: colors.background,
        body: const SizedBox.shrink(),
      );
    }

    final progress = (_currentIndex + 1) / total;
    final isFirst = _currentIndex == 0;
    final isLast = _currentIndex == total - 1;

    return Scaffold(
      backgroundColor: colors.background,
      body: SafeArea(
        child: Column(
          children: [
            _buildTopBar(colors, progress, total, isFirst),
            Expanded(
              child: PageView.builder(
                controller: _pageController,
                physics: const NeverScrollableScrollPhysics(),
                itemCount: total,
                itemBuilder: (context, index) {
                  final question = questions[index];
                  return _buildQuestionPage(colors, question);
                },
              ),
            ),
            _buildBottomBar(colors, isFirst, isLast),
          ],
        ),
      ),
    );
  }

  // ── Top bar ──────────────────────────────────────────────────────────────

  Widget _buildTopBar(
    AppColorsOf colors,
    double progress,
    int total,
    bool isFirst,
  ) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(
        AppDimens.spaceSm,
        AppDimens.spaceSm,
        AppDimens.spaceSm,
        AppDimens.spaceSm,
      ),
      child: Row(
        children: [
          // Back arrow (dims on first question).
          Opacity(
            opacity: isFirst ? 0.3 : 1.0,
            child: IconButton(
              icon: Icon(
                Icons.arrow_back,
                color: colors.textPrimary,
              ),
              onPressed: isFirst ? null : _goBack,
              tooltip: 'Back',
            ),
          ),

          // Question counter + progress bar.
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Question ${_currentIndex + 1} of $total',
                  style: AppTextStyles.labelMedium.copyWith(
                    color: colors.textSecondary,
                  ),
                ),
                const SizedBox(height: AppDimens.spaceXxs + 2),
                ClipRRect(
                  borderRadius: BorderRadius.circular(AppDimens.shapePill),
                  child: LinearProgressIndicator(
                    value: progress,
                    minHeight: 4,
                    backgroundColor: colors.surfaceRaised,
                    valueColor: AlwaysStoppedAnimation<Color>(
                      AppColors.categoryNutrition,
                    ),
                  ),
                ),
              ],
            ),
          ),

          // Skip all.
          Padding(
            padding: const EdgeInsets.only(left: AppDimens.spaceSm),
            child: TextButton(
              onPressed: _skipAll,
              style: TextButton.styleFrom(
                padding: const EdgeInsets.symmetric(
                  horizontal: AppDimens.spaceSm,
                ),
                minimumSize: const Size(0, 40),
                tapTargetSize: MaterialTapTargetSize.shrinkWrap,
              ),
              child: Text(
                'Skip all',
                style: AppTextStyles.labelMedium.copyWith(
                  color: colors.textSecondary,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  // ── Question page ────────────────────────────────────────────────────────

  Widget _buildQuestionPage(AppColorsOf colors, GuidedQuestion question) {
    // Resolve the food label for the question (uppercase, amber accent).
    final foods = widget.args.foods;
    final foodName = (question.foodIndex >= 0 &&
            question.foodIndex < foods.length)
        ? foods[question.foodIndex].foodName
        : '';

    return SingleChildScrollView(
      padding: const EdgeInsets.symmetric(
        horizontal: AppDimens.spaceMd,
        vertical: AppDimens.spaceSm,
      ),
      child: ZFadeSlideIn(
        key: ValueKey('page-${question.id}'),
        child: ZuralogCard(
          variant: ZCardVariant.feature,
          category: AppColors.categoryNutrition,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              if (foodName.isNotEmpty) ...[
                Text(
                  foodName.toUpperCase(),
                  style: AppTextStyles.labelMedium.copyWith(
                    color: AppColors.categoryNutrition,
                    letterSpacing: 0.8,
                  ),
                ),
                const SizedBox(height: AppDimens.spaceXs),
              ],
              Text(
                question.question,
                style: AppTextStyles.titleMedium.copyWith(
                  color: colors.textPrimary,
                ),
              ),
              const SizedBox(height: AppDimens.spaceLg),
              _buildComponent(colors, question),
            ],
          ),
        ),
      ),
    );
  }

  // ── Component router ────────────────────────────────────────────────────

  Widget _buildComponent(AppColorsOf colors, GuidedQuestion question) {
    final answer = _answers[question.id];
    switch (question.componentType) {
      case GuidedComponentType.slider:
        return _SliderQuestion(
          key: ValueKey('slider-${question.id}'),
          question: question,
          value: answer,
          onChanged: (v) => _setAnswer(question.id, v),
        );
      case GuidedComponentType.buttonGroup:
        return _ButtonGroupQuestion(
          key: ValueKey('buttons-${question.id}'),
          question: question,
          value: answer,
          onChanged: (v) => _setAnswer(question.id, v),
        );
      case GuidedComponentType.numberStepper:
        return _NumberStepperQuestion(
          key: ValueKey('stepper-${question.id}'),
          question: question,
          value: answer,
          onChanged: (v) => _setAnswer(question.id, v),
        );
      case GuidedComponentType.sizePicker:
        return _SizePickerQuestion(
          key: ValueKey('size-${question.id}'),
          question: question,
          value: answer,
          onChanged: (v) => _setAnswer(question.id, v),
        );
      case GuidedComponentType.yesNo:
        return _YesNoQuestion(
          key: ValueKey('yesno-${question.id}'),
          question: question,
          value: answer,
          onChanged: (v) => _setAnswer(question.id, v),
        );
      case GuidedComponentType.freeText:
        return _FreeTextQuestion(
          key: ValueKey('text-${question.id}'),
          question: question,
          controller: _controllerFor(question.id, answer),
        );
      case GuidedComponentType.unknown:
        return const _UnsupportedQuestion();
    }
  }

  // ── Bottom bar ───────────────────────────────────────────────────────────

  Widget _buildBottomBar(AppColorsOf colors, bool isFirst, bool isLast) {
    return Padding(
      padding: EdgeInsets.fromLTRB(
        AppDimens.spaceMd,
        AppDimens.spaceSm,
        AppDimens.spaceMd,
        MediaQuery.of(context).padding.bottom + AppDimens.spaceSm,
      ),
      child: Row(
        children: [
          // Back.
          Expanded(
            child: ZButton(
              label: 'Back',
              variant: ZButtonVariant.secondary,
              size: ZButtonSize.medium,
              onPressed: isFirst ? null : _goBack,
            ),
          ),
          const SizedBox(width: AppDimens.spaceSm),
          // Skip.
          ZButton(
            label: 'Skip',
            variant: ZButtonVariant.text,
            size: ZButtonSize.medium,
            isFullWidth: false,
            onPressed: _skipCurrent,
          ),
          const SizedBox(width: AppDimens.spaceSm),
          // Next / Finish.
          Expanded(
            child: ZButton(
              label: isLast ? 'Finish' : 'Next',
              size: ZButtonSize.medium,
              onPressed: _goNext,
            ),
          ),
        ],
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
//  Renderers
// ─────────────────────────────────────────────────────────────────────────────

// Utility: coerce a possibly-double value to a safe double within bounds.
double _asDouble(Object? value, double fallback) {
  if (value is num) return value.toDouble();
  if (value is String) return double.tryParse(value) ?? fallback;
  return fallback;
}

// ── Slider ──────────────────────────────────────────────────────────────────

class _SliderQuestion extends StatefulWidget {
  const _SliderQuestion({
    super.key,
    required this.question,
    required this.value,
    required this.onChanged,
  });

  final GuidedQuestion question;
  final Object? value;
  final ValueChanged<double> onChanged;

  @override
  State<_SliderQuestion> createState() => _SliderQuestionState();
}

class _SliderQuestionState extends State<_SliderQuestion> {
  late double _current;

  double get _min => widget.question.min ?? 0.0;
  double get _max {
    final raw = widget.question.max ?? 100.0;
    return raw <= _min ? _min + 1.0 : raw;
  }

  double? get _step => widget.question.step;

  @override
  void initState() {
    super.initState();
    _current = _snap(_asDouble(widget.value, _min));
  }

  double _snap(double value) {
    final clamped = value.clamp(_min, _max);
    final step = _step;
    if (step == null || step <= 0) return clamped;
    final steps = ((clamped - _min) / step).round();
    return (_min + steps * step).clamp(_min, _max);
  }

  @override
  Widget build(BuildContext context) {
    final colors = AppColorsOf(context);
    final unit = widget.question.unit ?? '';
    final formatted = _current == _current.truncateToDouble()
        ? _current.toInt().toString()
        : _current.toStringAsFixed(1);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        // Current value display (amber).
        Center(
          child: RichText(
            text: TextSpan(
              style: AppTextStyles.displaySmall.copyWith(
                color: AppColors.categoryNutrition,
              ),
              children: [
                TextSpan(text: formatted),
                if (unit.isNotEmpty)
                  TextSpan(
                    text: ' $unit',
                    style: AppTextStyles.titleMedium.copyWith(
                      color: AppColors.categoryNutrition,
                    ),
                  ),
              ],
            ),
          ),
        ),
        const SizedBox(height: AppDimens.spaceSm),
        ZSlider(
          value: _current,
          min: _min,
          max: _max,
          onChanged: (v) {
            final snapped = _snap(v);
            if (snapped == _current) return;
            setState(() => _current = snapped);
            widget.onChanged(snapped);
          },
        ),
        const SizedBox(height: AppDimens.spaceXs),
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text(
              '${_min.toStringAsFixed(_min == _min.truncateToDouble() ? 0 : 1)}'
              '${unit.isNotEmpty ? ' $unit' : ''}',
              style: AppTextStyles.bodySmall.copyWith(
                color: colors.textSecondary,
              ),
            ),
            Text(
              '${_max.toStringAsFixed(_max == _max.truncateToDouble() ? 0 : 1)}'
              '${unit.isNotEmpty ? ' $unit' : ''}',
              style: AppTextStyles.bodySmall.copyWith(
                color: colors.textSecondary,
              ),
            ),
          ],
        ),
      ],
    );
  }
}

// ── Button group (single-select chip wrap) ─────────────────────────────────

class _ButtonGroupQuestion extends StatefulWidget {
  const _ButtonGroupQuestion({
    super.key,
    required this.question,
    required this.value,
    required this.onChanged,
  });

  final GuidedQuestion question;
  final Object? value;
  final ValueChanged<String> onChanged;

  @override
  State<_ButtonGroupQuestion> createState() => _ButtonGroupQuestionState();
}

class _ButtonGroupQuestionState extends State<_ButtonGroupQuestion> {
  String? _selected;

  @override
  void initState() {
    super.initState();
    _selected = widget.value?.toString();
  }

  @override
  Widget build(BuildContext context) {
    final options = widget.question.options ?? const <String>[];
    if (options.isEmpty) {
      return const _UnsupportedQuestion();
    }

    return Wrap(
      spacing: AppDimens.spaceSm,
      runSpacing: AppDimens.spaceSm,
      children: options.map((option) {
        final isActive = _selected == option;
        return ZChip(
          label: option,
          isActive: isActive,
          onTap: () {
            setState(() => _selected = option);
            widget.onChanged(option);
          },
        );
      }).toList(),
    );
  }
}

// ── Number stepper (integer-only) ──────────────────────────────────────────

class _NumberStepperQuestion extends StatefulWidget {
  const _NumberStepperQuestion({
    super.key,
    required this.question,
    required this.value,
    required this.onChanged,
  });

  final GuidedQuestion question;
  final Object? value;

  /// Answers are stored as doubles to keep the parent map consistent with
  /// the slider component, even though the stepper only lets users pick ints.
  final ValueChanged<double> onChanged;

  @override
  State<_NumberStepperQuestion> createState() => _NumberStepperQuestionState();
}

class _NumberStepperQuestionState extends State<_NumberStepperQuestion> {
  late int _current;
  late int _min;
  late int _max;
  late int _step;

  @override
  void initState() {
    super.initState();
    _min = (widget.question.min ?? 0).round();
    final rawMax = (widget.question.max ?? 99).round();
    _max = rawMax <= _min ? _min + 1 : rawMax;
    final rawStep = (widget.question.step ?? 1).round();
    _step = rawStep <= 0 ? 1 : rawStep;
    final initial = _asDouble(widget.value, _min.toDouble()).round();
    _current = initial.clamp(_min, _max);
  }

  @override
  Widget build(BuildContext context) {
    final colors = AppColorsOf(context);
    final unit = widget.question.unit ?? '';

    return Column(
      children: [
        Center(
          child: ZNumberStepper(
            value: _current,
            min: _min,
            max: _max,
            step: _step,
            onChanged: (v) {
              setState(() => _current = v);
              widget.onChanged(v.toDouble());
            },
          ),
        ),
        if (unit.isNotEmpty) ...[
          const SizedBox(height: AppDimens.spaceXs),
          Text(
            unit,
            style: AppTextStyles.bodySmall.copyWith(
              color: colors.textSecondary,
            ),
          ),
        ],
      ],
    );
  }
}

// ── Size picker (visually delegates to the button group) ───────────────────

class _SizePickerQuestion extends StatelessWidget {
  const _SizePickerQuestion({
    super.key,
    required this.question,
    required this.value,
    required this.onChanged,
  });

  final GuidedQuestion question;
  final Object? value;
  final ValueChanged<String> onChanged;

  @override
  Widget build(BuildContext context) {
    return _ButtonGroupQuestion(
      question: question,
      value: value,
      onChanged: onChanged,
    );
  }
}

// ── Yes / No ────────────────────────────────────────────────────────────────

class _YesNoQuestion extends StatefulWidget {
  const _YesNoQuestion({
    super.key,
    required this.question,
    required this.value,
    required this.onChanged,
  });

  final GuidedQuestion question;
  final Object? value;
  final ValueChanged<bool> onChanged;

  @override
  State<_YesNoQuestion> createState() => _YesNoQuestionState();
}

class _YesNoQuestionState extends State<_YesNoQuestion> {
  bool? _selected;

  @override
  void initState() {
    super.initState();
    final v = widget.value;
    if (v is bool) {
      _selected = v;
    } else if (v is String) {
      final lower = v.toLowerCase();
      if (lower == 'yes' || lower == 'true') _selected = true;
      if (lower == 'no' || lower == 'false') _selected = false;
    }
  }

  void _choose(bool value) {
    setState(() => _selected = value);
    widget.onChanged(value);
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Expanded(
          child: ZButton(
            label: 'Yes',
            size: ZButtonSize.medium,
            variant: _selected == true
                ? ZButtonVariant.primary
                : ZButtonVariant.secondary,
            onPressed: () => _choose(true),
          ),
        ),
        const SizedBox(width: AppDimens.spaceSm),
        Expanded(
          child: ZButton(
            label: 'No',
            size: ZButtonSize.medium,
            variant: _selected == false
                ? ZButtonVariant.primary
                : ZButtonVariant.secondary,
            onPressed: () => _choose(false),
          ),
        ),
      ],
    );
  }
}

// ── Free text ──────────────────────────────────────────────────────────────

class _FreeTextQuestion extends StatefulWidget {
  const _FreeTextQuestion({
    super.key,
    required this.question,
    required this.controller,
  });

  final GuidedQuestion question;

  /// Controller owned by the parent screen — not disposed here.
  final TextEditingController controller;

  @override
  State<_FreeTextQuestion> createState() => _FreeTextQuestionState();
}

class _FreeTextQuestionState extends State<_FreeTextQuestion> {
  @override
  Widget build(BuildContext context) {
    return ZTextArea(
      controller: widget.controller,
      placeholder: 'Type your answer...',
      minLines: 3,
      maxLines: 6,
    );
  }
}

// ── Unsupported fallback ───────────────────────────────────────────────────

class _UnsupportedQuestion extends StatelessWidget {
  const _UnsupportedQuestion();

  @override
  Widget build(BuildContext context) {
    final colors = AppColorsOf(context);
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Icon(
          Icons.info_outline,
          size: AppDimens.iconMd,
          color: colors.textSecondary,
        ),
        const SizedBox(width: AppDimens.spaceSm),
        Expanded(
          child: Text(
            'This question can\'t be shown yet. Tap Skip to continue.',
            style: AppTextStyles.bodyMedium.copyWith(
              color: colors.textSecondary,
            ),
          ),
        ),
      ],
    );
  }
}
