"""add_user_profile_fields

Revision ID: 050d7af3bdcf
Revises: c8d60f5c8771
Create Date: 2026-02-23 17:02:47.715549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '050d7af3bdcf'
down_revision: Union[str, Sequence[str], None] = 'c8d60f5c8771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use IF NOT EXISTS to be idempotent — columns may already exist in the DB.
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name VARCHAR")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS nickname VARCHAR")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS birthday DATE")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR")
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_complete BOOLEAN NOT NULL DEFAULT false")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_complete')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
