"""add_user_profile_fields

Revision ID: 050d7af3bdcf
Revises: c8d60f5c8771
Create Date: 2026-02-23 17:02:47.715549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '050d7af3bdcf'
down_revision: Union[str, Sequence[str], None] = 'c8d60f5c8771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True, comment="Full display name, e.g. 'Alex Johnson'"))
    op.add_column('users', sa.Column('nickname', sa.String(), nullable=True, comment="What the AI coach calls the user, e.g. 'Alex'"))
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True, comment="User's date of birth for age calculation"))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True, comment='Self-identified gender (free text, optional)'))
    op.add_column('users', sa.Column('onboarding_complete', sa.Boolean(), server_default='false', nullable=False, comment='True once the user has completed the profile questionnaire'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_complete')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
