"""add_daily_health_metrics_table

Revision ID: d09d4fac7796
Revises: 050d7af3bdcf
Create Date: 2026-02-26 22:53:28.606681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09d4fac7796'
down_revision: Union[str, Sequence[str], None] = '050d7af3bdcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_health_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('active_calories', sa.Integer(), nullable=True),
    sa.Column('resting_heart_rate', sa.Float(), nullable=True),
    sa.Column('hrv_ms', sa.Float(), nullable=True),
    sa.Column('vo2_max', sa.Float(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('flights_climbed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'date', name='uq_daily_metrics_user_source_date')
    )
    op.create_index(op.f('ix_daily_health_metrics_user_id'), 'daily_health_metrics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_health_metrics_user_id'), table_name='daily_health_metrics')
    op.drop_table('daily_health_metrics')
    # ### end Alembic commands ###
