"""Insight model — AI-generated daily health insight cards.

Each insight is a prioritised card surfaced to the user's dashboard.
Insights are generated by the Celery pipeline after health data ingest
and are displayed until dismissed by the user.

See INSIGHT_TYPES for the full list of valid type values.

Categories:
    Trend signals      — trend_decline, trend_improvement
    Goal signals       — goal_nudge, goal_at_risk, goal_streak
    Anomaly signals    — anomaly_alert
    Correlation        — correlation_discovery
    Streak signals     — streak_milestone
    Compound patterns  — compound_weight_plateau, compound_overtraining_risk,
                         compound_sleep_debt, compound_deficit_too_deep,
                         compound_workout_collapse, compound_recovery_peak,
                         compound_stress_cascade, compound_dehydration_pattern,
                         compound_weekend_gap, compound_event_on_track
    Data quality       — data_quality
    Onboarding         — welcome
    Summary            — sleep_analysis, activity_progress, nutrition_summary
"""

import uuid
from datetime import date

from sqlalchemy import Date, DateTime, Integer, JSON, String
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.database import Base

# ---------------------------------------------------------------------------
# Valid insight type values — kept as a module constant so callers can
# validate without importing a heavyweight enum.
# ---------------------------------------------------------------------------
INSIGHT_TYPES: tuple[str, ...] = (
    # Existing
    "sleep_analysis",
    "activity_progress",
    "nutrition_summary",
    "anomaly_alert",
    "goal_nudge",
    "correlation_discovery",
    "streak_milestone",
    "welcome",
    # New trend types
    "trend_decline",
    "trend_improvement",
    # New goal types
    "goal_at_risk",
    "goal_streak",
    # New compound cross-domain patterns
    "compound_weight_plateau",
    "compound_overtraining_risk",
    "compound_sleep_debt",
    "compound_deficit_too_deep",
    "compound_workout_collapse",
    "compound_recovery_peak",
    "compound_stress_cascade",
    "compound_dehydration_pattern",
    "compound_weekend_gap",
    "compound_event_on_track",
    # Data quality
    "data_quality",
)


class Insight(Base):
    """An AI-generated health insight card for a single user.

    Insight cards are written by the Celery insight pipeline and consumed
    by the mobile app's dashboard. Cards remain visible until the user
    explicitly dismisses them (``dismissed_at`` is set). Read state is
    tracked separately (``read_at``) so the app can render an unread badge
    without hiding the card.

    Priority follows a 1–10 scale where **1 is the highest priority** and
    10 is the lowest. The GET endpoint orders by priority ASC so the most
    urgent card is always first.

    Attributes:
        id: UUID primary key (auto-generated).
        user_id: Owner's user ID (indexed for fast lookups).
        type: Insight category — one of ``INSIGHT_TYPES``.
        title: Short headline shown on the card (max ~80 chars in practice).
        body: Full card body text (1–3 sentences).
        data: Arbitrary JSON payload for rich card rendering — chart values,
            source metric names, numeric deltas, etc. Defaults to ``{}``.
        reasoning: Optional AI explanation of why this insight was surfaced.
            Populated by LLM-backed generators; ``None`` for rule-based ones.
        priority: Display priority (1 = highest urgency, 10 = lowest).
            Default is ``5`` (neutral).
        created_at: Server-side row creation timestamp (UTC).
        read_at: Timestamp when the user first viewed the card. ``None``
            until the client sends a ``PATCH`` with ``action="read"``.
        dismissed_at: Timestamp when the user dismissed the card. ``None``
            until dismissed. Dismissed cards are excluded from GET responses.
    """

    __tablename__ = "insights"

    id: Mapped[str] = mapped_column(
        String,
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )
    user_id: Mapped[str] = mapped_column(
        String,
        index=True,
        nullable=False,
    )
    type: Mapped[str] = mapped_column(
        String,
        nullable=False,
        comment=f"One of: {', '.join(INSIGHT_TYPES)}",
    )
    title: Mapped[str] = mapped_column(
        String,
        nullable=False,
    )
    body: Mapped[str] = mapped_column(
        String,
        nullable=False,
    )
    data: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=dict,
        server_default="{}",
        comment="Chart data, source metrics, numeric deltas — anything the card UI needs",
    )
    reasoning: Mapped[str | None] = mapped_column(
        String,
        nullable=True,
        comment="Optional LLM explanation of why this insight was generated",
    )
    priority: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=5,
        server_default="5",
        comment="1 = highest priority, 10 = lowest. GET orders by ASC.",
    )
    created_at: Mapped[str] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    read_at: Mapped[str | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Set when the client sends PATCH action=read",
    )
    dismissed_at: Mapped[str | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Set when the client sends PATCH action=dismiss. Hides card from GET.",
    )
    updated_at: Mapped[str | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Set on upsert when an existing insight is refreshed",
    )
    generation_date: Mapped[date | None] = mapped_column(
        Date,
        nullable=True,
        comment="Date in the user's local timezone (YYYY-MM-DD). Used for the daily date-lock check.",
    )
    signal_type: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        comment="Raw signal_type from InsightSignalDetector (e.g. trend_decline, compound_overtraining_risk). Nullable for legacy rows.",
    )
