"""
Zuralog Cloud Brain — Reports API.

Endpoints:
  GET /api/v1/reports                         — List saved reports for the user.
  GET /api/v1/reports/generate                — Generate a report on-demand.
  GET /api/v1/reports/{report_id}             — Retrieve a specific saved report.

All endpoints are auth-guarded via ``get_authenticated_user_id``.

Note: The ``reports`` table migration (d4e5f6a7b8c9) must be applied for
the list/get endpoints to function.  Until the migration runs, those
endpoints return an empty result set rather than 500 — graceful degradation
is handled via try/except around DB queries.
"""

import logging
import uuid
from datetime import date, datetime, timezone
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Query, status
from pydantic import BaseModel, ConfigDict
from sqlalchemy import JSON, Column, DateTime, String, select, text
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.v1.deps import get_authenticated_user_id
from app.database import Base, get_db
from app.services.report_generator import ReportGenerator

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/reports", tags=["reports"])


# ---------------------------------------------------------------------------
# Inline ORM model (avoids importing the not-yet-migrated model from models/)
# ---------------------------------------------------------------------------


class Report(Base):
    """Saved health report row.

    Reports are generated by ``ReportGenerator`` and persisted here so
    the client can retrieve them later without re-computation.

    Attributes:
        id: UUID primary key (auto-generated).
        user_id: Owner's user ID.
        type: Report period type — ``"weekly"`` or ``"monthly"``.
        period_start: ISO date string (YYYY-MM-DD) for the period start.
        period_end: ISO date string (YYYY-MM-DD) for the period end.
        data: Full report payload as JSON.
        created_at: Server-side creation timestamp (UTC).
    """

    __tablename__ = "reports"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, index=True, nullable=False)
    type = Column(String, nullable=False)
    period_start = Column(String, nullable=False)
    period_end = Column(String, nullable=False)
    data = Column(JSON, nullable=False, default=dict)
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )


# ---------------------------------------------------------------------------
# Pydantic schemas
# ---------------------------------------------------------------------------


class ReportSummaryResponse(BaseModel):
    """Brief report metadata returned in list responses.

    Attributes:
        id: Report UUID.
        type: ``"weekly"`` or ``"monthly"``.
        period_start: ISO date string.
        period_end: ISO date string.
        created_at: ISO-8601 creation timestamp.
    """

    id: str
    type: str
    period_start: str
    period_end: str
    created_at: str

    model_config = ConfigDict(from_attributes=True)


class ReportDetailResponse(ReportSummaryResponse):
    """Full report including the generated data payload.

    Extends ``ReportSummaryResponse`` with the ``data`` field.

    Attributes:
        data: Full report payload dict.
    """

    data: dict[str, Any]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _dt_str(value: Any) -> str:
    """Return an ISO-8601 string for a datetime value.

    Args:
        value: A ``datetime`` instance or string.

    Returns:
        ISO-8601 string, or empty string if conversion fails.
    """
    if value is None:
        return ""
    if isinstance(value, datetime):
        return value.isoformat()
    return str(value)


def _report_to_summary(row: Report) -> ReportSummaryResponse:
    """Convert a ``Report`` ORM row to a ``ReportSummaryResponse``.

    Args:
        row: The ORM instance to serialise.

    Returns:
        A ``ReportSummaryResponse``.
    """
    return ReportSummaryResponse(
        id=row.id,
        type=row.type,
        period_start=row.period_start,
        period_end=row.period_end,
        created_at=_dt_str(row.created_at),
    )


def _report_to_detail(row: Report) -> ReportDetailResponse:
    """Convert a ``Report`` ORM row to a ``ReportDetailResponse``.

    Args:
        row: The ORM instance to serialise.

    Returns:
        A ``ReportDetailResponse`` with the full data payload.
    """
    return ReportDetailResponse(
        id=row.id,
        type=row.type,
        period_start=row.period_start,
        period_end=row.period_end,
        created_at=_dt_str(row.created_at),
        data=row.data or {},
    )


# ---------------------------------------------------------------------------
# Endpoints — order matters: specific paths before parameterised paths
# ---------------------------------------------------------------------------


@router.get("/generate", summary="Generate a health report on-demand")
async def generate_report(
    user_id: str = Depends(get_authenticated_user_id),
    db: AsyncSession = Depends(get_db),
    type: str = Query("weekly", pattern="^(weekly|monthly)$", description="Report type"),
    date_str: str = Query(
        ...,
        alias="date",
        description="Period start date as YYYY-MM-DD (first day of week or month)",
    ),
) -> dict[str, Any]:
    """Generate a health report on-demand and optionally persist it.

    This endpoint does NOT require the ``reports`` table to exist — it
    queries ``daily_health_metrics`` directly and returns the report as a
    JSON response.  If the ``reports`` table exists, the result is also
    persisted for later retrieval.

    Args:
        user_id: Authenticated user ID (injected by dependency).
        db: Async database session.
        type: ``"weekly"`` or ``"monthly"``.
        date_str: Period start date (YYYY-MM-DD).  For weekly reports this
            should be Monday; for monthly reports this should be the 1st.

    Returns:
        Full report dict from ``ReportGenerator``.

    Raises:
        HTTPException: 400 if ``date`` is not a valid ISO date.
    """
    try:
        period_start = date.fromisoformat(date_str)
    except ValueError:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Invalid date format '{date_str}'. Expected YYYY-MM-DD.",
        )

    generator = ReportGenerator()

    if type == "weekly":
        report_data = await generator.generate_weekly(user_id, db, period_start)
    else:
        report_data = await generator.generate_monthly(user_id, db, period_start)

    # Attempt to persist — graceful no-op if the table doesn't exist yet.
    try:
        report_row = Report(
            id=str(uuid.uuid4()),
            user_id=user_id,
            type=type,
            period_start=report_data["period_start"],
            period_end=report_data["period_end"],
            data=report_data,
            created_at=datetime.now(timezone.utc),
        )
        db.add(report_row)
        await db.commit()
        logger.info(
            "generate_report: persisted report id=%s user=%s type=%s",
            report_row.id,
            user_id,
            type,
        )
    except Exception:
        logger.warning(
            "generate_report: could not persist report for user=%s "
            "(reports table may not exist yet)",
            user_id,
            exc_info=True,
        )
        await db.rollback()

    return report_data


@router.get("", summary="List saved reports")
async def list_reports(
    user_id: str = Depends(get_authenticated_user_id),
    db: AsyncSession = Depends(get_db),
    type: str | None = Query(None, pattern="^(weekly|monthly)$", description="Filter by report type"),
    limit: int = Query(10, ge=1, le=50, description="Maximum number of results"),
) -> dict[str, Any]:
    """Return a list of saved reports for the authenticated user.

    Reports are ordered by ``created_at`` DESC (most recent first).

    If the ``reports`` table does not yet exist (migration pending), the
    endpoint returns an empty list rather than raising a 500 error.

    Args:
        user_id: Authenticated user ID (injected by dependency).
        db: Async database session.
        type: Optional filter by report type (``"weekly"`` or ``"monthly"``).
        limit: Maximum number of results (1–50, default 10).

    Returns:
        ``{ reports: [...], total }`` envelope.
    """
    try:
        stmt = (
            select(Report)
            .where(Report.user_id == user_id)
            .order_by(Report.created_at.desc())
            .limit(limit)
        )
        if type is not None:
            stmt = (
                select(Report)
                .where(Report.user_id == user_id, Report.type == type)
                .order_by(Report.created_at.desc())
                .limit(limit)
            )
        result = await db.execute(stmt)
        rows = result.scalars().all()
        summaries = [_report_to_summary(row).model_dump() for row in rows]
        return {"reports": summaries, "total": len(summaries)}
    except Exception:
        logger.warning(
            "list_reports: query failed for user=%s — reports table may not exist",
            user_id,
            exc_info=True,
        )
        return {"reports": [], "total": 0}


@router.get("/{report_id}", summary="Get a specific saved report")
async def get_report(
    report_id: str,
    user_id: str = Depends(get_authenticated_user_id),
    db: AsyncSession = Depends(get_db),
) -> dict[str, Any]:
    """Retrieve a specific saved report by ID.

    Args:
        report_id: UUID of the report to retrieve.
        user_id: Authenticated user ID (injected by dependency).
        db: Async database session.

    Returns:
        Full ``ReportDetailResponse`` dict.

    Raises:
        HTTPException: 404 if the report does not exist, belongs to a
            different user, or the reports table does not yet exist.
    """
    try:
        result = await db.execute(
            select(Report).where(
                Report.id == report_id,
                Report.user_id == user_id,
            )
        )
        row = result.scalar_one_or_none()
    except Exception:
        logger.warning(
            "get_report: query failed for report_id=%s user=%s — reports table may not exist",
            report_id,
            user_id,
            exc_info=True,
        )
        row = None

    if row is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Report not found.",
        )

    return _report_to_detail(row).model_dump()
